---
title: "Leaflet map"
format: html
```{r}
library(tidyverse)
library(leaflet)
library(readxl)
library(magrittr)
library(reshape2)
library(ggplot2)
library(ggsci)
```



```{r}
long1 <- c(5.8987,77.209)
lat1 <- c(51.9851,28.6139)
df_location1 <-data.frame(long1,lat1)

long2 <- c(5.8987,1.5209)
lat2 <- c(51.9851,41.5912)
df_location2 <-data.frame(long2,lat2)

long3 <- c(5.8987,9.1393)
lat3 <- c(51.9851,38.7223)
df_location3 <-data.frame(long3,lat3)

long4 <- c(5.8987,13.7373)
lat4 <- c(51.9851,51.0504)
df_location4 <-data.frame(long4,lat4)

long5 <- c(5.8987,13.7373)
lat5 <- c(51.9851,52.1307)
df_location5 <-data.frame(long5,lat5)

line_map<- leaflet(df_colormarker) %>% addTiles() %>%
  addAwesomeMarkers(~long, ~lat, icon=icons, label=~as.character(popup)) %>% 
  addPolylines(data = df_location1, lng = ~long1, lat = ~lat1,weight=5.364241)%>% 
  addPolylines(data = df_location2, lng = ~long2, lat = ~lat2,weight=4.205565) %>%
  addPolylines(data = df_location3, lng = ~long3, lat = ~lat3,weight=1.893636) %>% 
  addPolylines(data = df_location4, lng = ~long4, lat = ~lat4,weight=3.931758) %>% 
  addPolylines(data = df_location5, lng = ~long5, lat = ~lat5,weight=0.226458) 

line_map
```

